check exception=error exit(1)
